<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Collective Lease Application Form Virtual Personal Server & AIR KITARO Angel</title>
    <style rel="stylesheet">
        * {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 14px;
        }

        small {
            font-size: 12px;
            color: #666;
        }
    </style>
</head>

<body>
    <p>Dear <?php echo $user['name']; ?></p>
    <br>
    <p>
        Thank you for register as investor, your account has been approve by admininstrator<br>
        this is account where you can login app :
    </p>

    <table>
        <tr>
            <td> ID Account </td>
            <td>: <?php echo $user['id']; ?> </td>
        </tr>
        <tr>
            <td> Email </td>
            <td>: <?php echo $user['email']; ?> </td>
        </tr>

        <tr>
            <td> Password </td>
            <td>: <?php echo $user['note']; ?> </td>
        </tr>

    </table>


    <table bgcolor="#FFF3CD" cellpadding="3" width="100%">
        <Tr>
            <td align="center" width="50%">
                Link download  :
                <div><a href="https://www.kitaro21.com/play/" target="_blank">Google Play</a> </div>
            </td>

            <td align="center">
                Link Web Base :
                <div><a href="https://app.kitaro21.com/" target="_blank">Web Mobile</a> </div>
            </td>
        </Tr>
    </table>

    <br>
    <table bgcolor="#DDEEFF" width="100%">
        <thead>
            <tr>
                <td><strong>Auto Generate Letters</strong></td>
            </tr>
        </thead>
        <tbody>
            <Tr>

                <td>
                    <a href="<?php echo base_url(); ?>letter/investor/<?php echo $transactionCode; ?>" target="_blank">Investor statement letter</a>
                </td>
            </Tr>
            <Tr>
                <td>
                    <a href="<?php echo base_url(); ?>letter/power/<?php echo $transactionCode; ?>" target="_blank">General Power of Attorney</a>
                </td>
            </Tr>
        </tbody>

    </table>

    <hr>

    <small>This email generated by system, please do not reply to this email</small>
    </p>
</body>

</html>